### ISSUE TITLE
#feature - Unified footer

### ISSUE THREAD

**Issue by fovecsernyes** [fovecsernyes/pizza-ordering-system#22]
Right now the footer is added to every single html, but it is the same on every page. Please create unified (same on every page) footer with content and change it on every page (as the navigation bar) in the layout folder.

**Comment by fovecsernyes** [comment]
Can you give me some feedback about your progress? This issue is still in the "To do" column on the board.

**Comment by martonur** [comment]
I'm starting to work on the issue now.

**Comment by martonur** [comment]
The footer is changed to a unified one on every single html page. I've added a lame slogan to serve as a placeholder, IMO later we can add the social icons here instead of including them in the header.

P.S.: while I was looking through the html files I've found them a little ugly, some beautifying might be needed. (mainly indentation)

**Comment by fovecsernyes** [comment]
@martonur feel free to include social icons to the footer and do the indentation.
