### ISSUE TITLE
#feature - Login and user creation

### ISSUE THREAD

**Issue by fovecsernyes** [fovecsernyes/pizza-ordering-system#3]
Please investigate how we can manage users in django (sign up, log in, store data etc.). We need some info of the already implemented features in the framework.

**Comment by fovecsernyes** [comment]
legyszi feature/3-ra nevezd at a branchet, hogy feature/issue_number legyen mindenhol egysegesen. koszi.

**Comment by fovecsernyes** [comment]
@martinb214 ha elkedted már, akkor légyszi rakd in progressbe. Köszi

**Comment by martinb214** [comment]
Investigated and implemented user authentication functions:

- Sign up

- Log in/ Log out

- Reset password

Notes: 
Right now we cannot send the reset password emails because we do not have any email service.
I'm creating new issues which coming from this task.

Tips to the tester:
Create new user, log in, log out, reset password. You can find pw reset emails under src/sent_emails, use the link from the files created there. Important: to improve security New password sent page is triggered every time when user clicks Change my password button but email is created only when user entered registered email.
